// The data model of the board. This file, and every file in src/domain,
// never imports React: the domain is testable without a browser.
//
// Shape: two flat collections joined by Card.listId, not lists carrying their
// cards. See docs/DECISIONS.md, ADR-007.
//
// Every field is readonly, so the compiler rejects an in place mutation
// instead of relying on discipline. This also makes cards.sort() impossible,
// which matters: sort() mutates its receiver, so sorting for display would
// have mutated the state. The readonly type forces [...cards].sort().
//
// Switching the data source from localStorage to the API (ADR-009) did not
// change a single field here. The shape was chosen to mirror the back API
// resources (ADR-007), and that bet held.
//
// Scope note: these types are erased at compile time. They constrain our own
// code, they validate nothing at runtime. The mapping in src/api/dto.ts picks
// the fields one by one, so nothing the API adds can leak in here, but it does
// not check their types either. See ADR-020 for why, and for what it would
// take to add.

/** A task. Lives in exactly one list, named by listId. */
export type Card = {
  /** Generated by the server, never by the front. See ADR-011. */
  readonly id: string;
  readonly title: string;
  /** Never null. The server defaults it to an empty string (consigne p.2). */
  readonly description: string;
  /**
   * Sort key inside the parent list, assigned BY THE SERVER as last position
   * plus one (ADR-011). The front never computes it.
   * Gaps are expected after a deletion and are harmless: nothing reindexes,
   * and reading always sorts on this value.
   */
  readonly position: number;
  /** The single representation of the card to list relation. */
  readonly listId: string;
};

/** A column of the board. Does not carry its cards, see ADR-007. */
export type List = {
  /** Generated by the server, never by the front. See ADR-011. */
  readonly id: string;
  readonly title: string;
  /** Sort key inside the board, same rule as Card.position. */
  readonly position: number;
};

/** The whole board. The only state the application holds. */
export type Board = {
  readonly lists: readonly List[];
  readonly cards: readonly Card[];
};

/**
 * A board with no list and no card. The starting point of a session.
 *
 * NOT what a failed load returns, and this changed with ADR-009. Answering an
 * empty board on failure would swallow the outage: the user would read
 * "aucune colonne" while the server is down, and believe the data was lost.
 * A failed load raises, and use-board turns it into an error state.
 * Loading, empty and error are three distinct states, see FRONT-10 and FRONT-11.
 */
export const emptyBoard: Board = { lists: [], cards: [] };

/**
 * The fields of a card a user may change.
 *
 * Optional means "leave this one alone", so updating the title never clears
 * the description. An empty string is a real value, not an absence: it is how
 * a description gets emptied.
 *
 * listId was added at FRONT-38: moving a card is a PATCH like any other,
 * and the flat shape of ADR-007 means the state has nothing to reorganise.
 */
export type CardPatch = {
  readonly title?: string;
  readonly description?: string;
  readonly listId?: string;
};

/**
 * The fields of a column a user may change.
 *
 * Symmetric with CardPatch, and for the same reason: an absent field means
 * "leave this one alone". Only the title is changeable, since identifier and
 * position belong to the server (ADR-011).
 */
export type ListPatch = {
  readonly title?: string;
};
